# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3578c6428a4885b3cd97cdab0fbafb528f365a6d6eb2965a9fdc3aaf3b6c4f77e1f30cb9303034c8ee9ee8d19e8d4d7ac68676093470667ded3193c3124e4a99

test:
  secret_key_base: 1e4a633bff00ded58a99f02af165ed58857554ee90d7a5960fc583dbb38fd92f5dc95663eb5eb67b185f678fea1d1bc165b3fb7eb25c05410a5b2e89965d1345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
